name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para Google Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Construir y subir imagen Docker a Artifact Registry
        run: |
          docker build -t us-docker.pkg.dev/caso3uhe/mi-repo-docker/caso3UHE:latest .
          docker push us-docker.pkg.dev/caso3uhe/mi-repo-docker/caso3UHE:latest

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy caso3UHE --image us-docker.pkg.dev/caso3uhe/mi-repo-docker/caso3UHE:latest --platform managed --region us-central1 --allow-unauthenticated
        